// Defaults — override in config.local.js (gitignored)
var CONFIG = CONFIG || {};
CONFIG.SUPABASE_URL = CONFIG.SUPABASE_URL || '';
CONFIG.SUPABASE_PUBLISHABLE_KEY = CONFIG.SUPABASE_PUBLISHABLE_KEY || '';
